name: nps_sdk
description: API with which you can interact with NPS's platform.
version: 1.0.0

homepage: https://github.com/Ingenico-NPS-Latam/nps-sdk-dart
documentation: https://developers.nps.com.ar/

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  firebase_remote_config: ^4.3.17
  http: ^1.1.1
  xml: ^6.5.0
  xml2json: ^6.2.2

